# Generated by Django 3.1.2 on 2020-10-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('cod_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('descrip_estado', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('cod_oferta', models.IntegerField(primary_key=True, serialize=False)),
                ('permite_cancelacion', models.CharField(blank=True, max_length=2, null=True)),
                ('fecha_inicio_oferta', models.DateField(blank=True, null=True)),
                ('fecha_fin_oferta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'oferta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfertaAlquiler',
            fields=[
                ('cod_oferta', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_propiedad', models.IntegerField()),
                ('fec_solicitud', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oferta_alquiler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropCasa',
            fields=[
                ('cod_propiedad', models.IntegerField(primary_key=True, serialize=False)),
                ('patio', models.CharField(blank=True, max_length=2, null=True)),
                ('pileta', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'prop_casa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropDpto',
            fields=[
                ('cod_propiedad', models.IntegerField(primary_key=True, serialize=False)),
                ('frente', models.CharField(blank=True, max_length=2, null=True)),
                ('contrafrente', models.CharField(blank=True, max_length=2, null=True)),
                ('espacios_comunes', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'prop_dpto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropHabitacion',
            fields=[
                ('cod_propiedad', models.IntegerField(primary_key=True, serialize=False)),
                ('banio_individual', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'prop_habitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('cod_propiedad', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_propiedad', models.IntegerField(blank=True, null=True)),
                ('mtrs2_cubiertos', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mtrs2_semicubiertos', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('cant_banios', models.IntegerField(blank=True, null=True)),
                ('cant_ambientes', models.IntegerField(blank=True, null=True)),
                ('permite_cancelacion', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'propiedad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropiedadOferta',
            fields=[
                ('cod_oferta', models.IntegerField()),
                ('cod_propiedad', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'propiedad_oferta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('tipo_propiedad', models.IntegerField(primary_key=True, serialize=False)),
                ('descrip_tipo_propiedad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipo_propiedad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('cod_zona', models.IntegerField(primary_key=True, serialize=False)),
                ('descrip_zona', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'zona',
                'managed': False,
            },
        ),
    ]
