# Generated by Django 3.1.2 on 2020-10-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlquilerPropiedad',
            fields=[
                ('cod_propiedad', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_persona', models.IntegerField()),
                ('importe_alquiler', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fec_alquiler_desde', models.DateField(blank=True, null=True)),
                ('fec_alquiler_hasta', models.DateField(blank=True, null=True)),
                ('cant_personas', models.IntegerField(blank=True, null=True)),
                ('importe_senia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'alquiler_propiedad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPropiedad',
            fields=[
                ('cod_propiedad', models.IntegerField()),
                ('cod_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_estado_desde', models.DateField(blank=True, null=True)),
                ('fecha_estado_hasta', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estado_propiedad',
                'managed': False,
            },
        ),
    ]
